#!/bin/bash

PROJECT="$1"

if [[ -z "$PROJECT" ]]; then
    echo "project name required"
    exit 1
fi

# create .dbpass if it doesn't exist
[[ -e ".dbpass" ]] || echo "$(< /dev/urandom tr -dc 'A-Za-z0-9!%^*}(+=' | head -c 40)" > .dbpass

# read .dbpass to variable
password=$(<.dbpass)

query="Found '.dbpass' file. Do you want to continue creating a database and user with this password? (y/n): "

read -p "$query" answer

if [[ "$answer" =~ ^[Yy]$ ]]; then
    echo ":: creating db $PROJECT"
    temp_file=$(mktemp)
    echo $temp_file
    cat << EOF > $temp_file
CREATE DATABASE $PROJECT ENCODING 'utf8';
CREATE USER $PROJECT WITH PASSWORD '$password';
ALTER ROLE $PROJECT SET client_encoding TO 'utf8';
ALTER ROLE $PROJECT SET default_transaction_isolation TO 'read committed';
ALTER ROLE $PROJECT SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE $PROJECT TO $PROJECT;
EOF

    sudo chown db:db $temp_file
    sudo su - db -c "psql -f $temp_file"
    sudo rm $temp_file
else
    exit 0
fi
